### ISSUE TITLE
An unrecognizable item if there is no space before the currency

### ISSUE THREAD

**Issue by xhelgx** [cobr123/ruspovar#1]
<img width="462" alt="изображение" src="https://user-images.githubusercontent.com/43569248/232805032-85dfd91a-10c9-4899-a3d8-3e9d25d3eeb9.png">

Maybe just cut off `рсд` and possible spellings from the end of the line?

**Comment by cobr123** [comment]
fixed https://github.com/cobr123/ruspovar/commit/5cff38a28dc93a70974eb20fb455b73d045eddbb
